/**
 * next/og (Satori) cannot shape Urdu: it rejects Noto Naskh's contextual
 * substitution tables. So the few fixed Urdu phrases used in Open Graph
 * images are rendered here with real Chromium and saved as base64 PNGs in
 * src/lib/og-urdu.generated.ts. Re-run after changing those Urdu strings:
 *
 *   npx tsx scripts/generate-og-urdu.ts
 */
import { chromium } from 'playwright';
import { writeFile } from 'node:fs/promises';
import ur from '../src/i18n/ur';

type Phrase = { key: string; text: string; font: 'nastaliq' | 'naskh'; weight: number; size: number; color: string };

const PHRASES: Phrase[] = [
  { key: 'line1', text: ur.home.hero.line1, font: 'nastaliq', weight: 700, size: 92, color: '#F2F2EE' },
  { key: 'line2', text: ur.home.hero.line2, font: 'nastaliq', weight: 700, size: 92, color: '#E5484D' },
  { key: 'footer', text: ur.share.card.footer, font: 'naskh', weight: 700, size: 34, color: '#FFB81C' },
  { key: 'numberTitle', text: ur.share.card.numberTitle, font: 'naskh', weight: 700, size: 46, color: '#F2F2EE' },
  { key: 'unitOne', text: ur.share.card.numberUnit.one, font: 'naskh', weight: 700, size: 60, color: '#F2F2EE' },
  { key: 'unitOther', text: ur.share.card.numberUnit.other, font: 'naskh', weight: 700, size: 60, color: '#F2F2EE' },
  { key: 'note', text: ur.share.card.numberNote, font: 'naskh', weight: 400, size: 30, color: '#A3A2BA' },
  { key: 'none', text: ur.number.emptyTitle, font: 'naskh', weight: 700, size: 60, color: '#F2F2EE' },
  { key: 'noneSafe', text: ur.number.emptyBody.split('۔')[0] + '۔', font: 'naskh', weight: 400, size: 34, color: '#A3A2BA' },
];

const html = `<!doctype html><html lang="ur" dir="rtl"><head><meta charset="utf-8">
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Noto+Naskh+Arabic:wght@400;700&family=Noto+Nastaliq+Urdu:wght@700&display=block">
<style>body{margin:0;background:transparent}span{display:inline-block;white-space:nowrap;padding:0.15em 0.25em;line-height:1.9}
.naskh{font-family:'Noto Naskh Arabic'}.nastaliq{font-family:'Noto Nastaliq Urdu';line-height:2.2}</style></head><body>
${PHRASES.map((p) => `<div><span id="${p.key}" class="${p.font}" style="font-size:${p.size}px;font-weight:${p.weight};color:${p.color}">${p.text}</span></div>`).join('')}
</body></html>`;

async function main() {
  const browser = await chromium.launch();
  const page = await browser.newPage({ deviceScaleFactor: 2 });
  await page.setContent(html, { waitUntil: 'networkidle' });
  await page.evaluate(() => document.fonts.ready);
  await page.waitForTimeout(300);

  const out: Record<string, { src: string; width: number; height: number }> = {};
  for (const p of PHRASES) {
    const el = page.locator(`#${p.key}`);
    const box = (await el.boundingBox())!;
    const png = await el.screenshot({ omitBackground: true });
    out[p.key] = { src: `data:image/png;base64,${png.toString('base64')}`, width: Math.round(box.width), height: Math.round(box.height) };
  }
  await browser.close();

  const body = `// Generated by scripts/generate-og-urdu.ts. Do not edit by hand.
  // Urdu phrases for Open Graph images, pre-shaped by Chromium (Satori cannot shape Urdu).
  export const OG_URDU = ${JSON.stringify(out, null, 1)} as const;
  `;
  await writeFile('src/lib/og-urdu.generated.ts', body);
  console.log('Wrote src/lib/og-urdu.generated.ts', Object.fromEntries(Object.entries(out).map(([k, v]) => [k, `${v.width}x${v.height}`])));
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
